# This workflow will install Python dependencies, and execute python scripts as per the given cron schedule
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

# Trigger Workflow every midnight UTC

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  #workflow_dispatch helps run workflow anytime with a single click.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute
      run: |
        python main.py ${{ secrets.ACCOUNT_SID }} ${{ secrets.AUTH_TOKEN }} ${{ secrets.NUMBERS }} 
